---
title: "Weight of Fish"
author: "Estevan Green"
date: "`r Sys.Date()`"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
---



```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
require(leaps)
```

# Predicting Fish Weight
## get data
```{r}
fishData=read.csv("Fish.csv")
```


## Perch
```{r}
perch = filter(fishData, Species == "Perch")
```

### Best Models
```{r}
models = regsubsets(Weight ~ Length1+Length2+Length3+Height+Width, data=perch,
                    nvmax=5)

summary(models)

res.sum <- summary(models)
Adj.R2 = which.max(res.sum$adjr2)
print(paste("best adjusted r-squared", Adj.R2))

results = data.frame(
  Adj.R2 = which.max(res.sum$adjr2),
  CP = which.min(res.sum$cp),
  BIC = which.min(res.sum$bic)
)
print(results)

```

the best two variables to predict weight are height and width.

### Best Two regressor model

```{r}
perchModel=lm(Weight~Height+Width,data = perch)
summary(perchModel)
```
For the best model adjust r squared was 0.94.

## Pike
```{r}
pike = filter(fishData, Species == "Pike")
```

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements